Minor tweeks to Fortran module handling to confusing ifort error output from a user
          FC linux-intel/obj/dm/f90-mod/petscdmplexmod.o
          FC linux-intel/obj/ksp/f90-mod/petsckspdefmod.o
/home/aizu/petsc/include/../src/ksp/f90-mod/petscksp.h(14): error #6457: This derived type name has not been declared.   [KSP]
      type(KSP), parameter :: PETSC_NULL_KSP = tKSP(0)
-----------^
/home/aizu/petsc/src/ksp/f90-mod/petsckspdefmod.F(46): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [PETSCKSPDEFDUMMY]  Check INCLUDE paths.   [PETSCKSPDEFDUMMY]
            use petsckspdefdummy
----------------^
/home/aizu/petsc/src/ksp/f90-mod/petsckspdefmod.F(51): error #6457: This derived type name has not been declared.   [TKSP]
            type(tKSP), intent(in) :: A,B
-----------------^
/home/aizu/petsc/src/ksp/f90-mod/petsckspdefmod.F(56): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [PETSCKSPDEFDUMMY]
            use petsckspdefdummy
----------------^
/home/aizu/petsc/src/ksp/f90-mod/petsckspdefmod.F(58): error #6457: This derived type name has not been declared.   [TKSP]
            type(tKSP), intent(in) :: A,B
-----------------^

   I have a newer version if ifort and do not get these errors (could be problem with the ifort version)

Commit-type: bug-fix, portability-fix
Reported-by: Aizuddin Mohamed <mrmaizu95@gmail.com>